<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rosidah Ahmad, Kamarul Ariffin Mansor. Ida Normaya Mohd Nasir, and Norin Rahayu Shamsudin">

<title>Statistics for Business and Social Sciences - 2&nbsp; Descriptive Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-estimation.html" rel="next">
<link href="./01-intro.html" rel="prev">
<link href="./cover2.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script defer="" data-domain="r4ds.hadley.nz" src="https://plausible.io/js/plausible.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-descriptive.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics for Business and Social Sciences</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-descriptive.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives:</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2.1</span> Introduction</a></li>
  <li><a href="#organizing-data" id="toc-organizing-data" class="nav-link" data-scroll-target="#organizing-data"><span class="header-section-number">2.2</span> Organizing Data</a></li>
  <li><a href="#numerical-descriptive-measures-ungrouped" id="toc-numerical-descriptive-measures-ungrouped" class="nav-link" data-scroll-target="#numerical-descriptive-measures-ungrouped"><span class="header-section-number">2.3</span> Numerical descriptive measures (ungrouped)</a>
  <ul class="collapse">
  <li><a href="#measures-of-central-tendency" id="toc-measures-of-central-tendency" class="nav-link" data-scroll-target="#measures-of-central-tendency"><span class="header-section-number">2.3.1</span> Measures of Central Tendency</a></li>
  <li><a href="#measure-of-variation" id="toc-measure-of-variation" class="nav-link" data-scroll-target="#measure-of-variation"><span class="header-section-number">2.3.2</span> Measure of variation</a></li>
  <li><a href="#measure-of-skewness" id="toc-measure-of-skewness" class="nav-link" data-scroll-target="#measure-of-skewness"><span class="header-section-number">2.3.3</span> Measure of skewness</a></li>
  <li><a href="#measures-of-position-q-q2-and-q3" id="toc-measures-of-position-q-q2-and-q3" class="nav-link" data-scroll-target="#measures-of-position-q-q2-and-q3"><span class="header-section-number">2.3.4</span> Measures of Position (Q, Q2, and Q3)</a></li>
  <li><a href="#box-and-whisker-plot" id="toc-box-and-whisker-plot" class="nav-link" data-scroll-target="#box-and-whisker-plot"><span class="header-section-number">2.3.5</span> Box-and-whisker plot</a></li>
  </ul></li>
  <li><a href="#spss-output-on-numerical-descriptive-statistics" id="toc-spss-output-on-numerical-descriptive-statistics" class="nav-link" data-scroll-target="#spss-output-on-numerical-descriptive-statistics"><span class="header-section-number">2.4</span> SPSS Output on Numerical Descriptive Statistics</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2"><span class="header-section-number">2.5</span> Exercise 2</a></li>
  <li><a href="#answers-to-exercise-2" id="toc-answers-to-exercise-2" class="nav-link" data-scroll-target="#answers-to-exercise-2"><span class="header-section-number">2.6</span> Answers to Exercise 2</a></li>
  <li><a href="#tutorial-2" id="toc-tutorial-2" class="nav-link" data-scroll-target="#tutorial-2"><span class="header-section-number">2.7</span> Tutorial 2</a></li>
  <li><a href="#answers-to-tutorial-2" id="toc-answers-to-tutorial-2" class="nav-link" data-scroll-target="#answers-to-tutorial-2"><span class="header-section-number">2.8</span> Answers to Tutorial 2</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives:</h2>
<ol type="1">
<li>Identify various ways to present collected data from survey of secondary sources</li>
<li>Use appropriate data presentation for a qualitative and quantitative data</li>
<li>Calculate the measures of central tendency, measure of variation, measure of skewness and measure of position for ungrouped data.</li>
</ol>
</section>
<section id="introduction" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">2.1</span> Introduction</h2>
<p>When conducting a statistical study, the researcher must gather data for the variable under study. For example, if a researcher wishes to study the number of road accidents in Malaysia for the past 2 years, he or she must gather the data from various departments. To describe the situation, draw conclusions, or make inferences about the event, the researcher must organize the data and present it in some meaningful way.</p>
<center>
<img src="images/ch2/picture1.png" class="img-fluid" width="600">
</center>
<p>The data can be presented in term of graphical approach or table and numerical descriptive measure for both qualitative dan quantitative data.</p>
</section>
<section id="organizing-data" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="organizing-data"><span class="header-section-number">2.2</span> Organizing Data</h2>
<p><strong>Charts and graphs</strong></p>
<ul>
<li>Frequency distributions are good ways to present the essential aspects of data collections in concise and understandable terms</li>
<li>Pictures are always more effective in displaying large data collections</li>
</ul>
<p><strong>Histogram</strong></p>
<ul>
<li>Frequently used to graphically present interval and ratio data</li>
<li>The adjacent bars indicate that a numerical range is being summarized by indicating the frequencies in arbitrarily chosen classes</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture2.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 1: Histogram – distribution of the ages (in months) of 50 children</figcaption><p></p>
</figure>
</div>
<p><strong>Frequency Polygon</strong></p>
<ul>
<li>Another common method for graphically presenting interval and ratio data</li>
<li>To construct a frequency polygon mark the frequencies on the vertical axis and the values of the variable being measured on the horizontal axis, as with the histogram.</li>
<li>If the purpose of presenting is to compare with other distributions, the frequency polygon provides a good summary of the data</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture3.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 2: Frequency Polygon – distribution of the ages (in months) of 50 children</figcaption><p></p>
</figure>
</div>
<p><strong>Ogive</strong></p>
<ul>
<li>A graph of a cumulative frequency distribution</li>
<li>Ogive is used when one wants to determine how many observations lie above or below a certain value in a distribution.</li>
<li>First cumulative frequency distribution is constructed</li>
<li>Cumulative frequencies are plotted at the upper-class limit of each category</li>
<li>Ogive can also be constructed for a relative frequency distribution.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture4.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 3: Ogive distribution of the ages (in months) of 50 children</figcaption><p></p>
</figure>
</div>
<p><strong>Pie Chart</strong></p>
<ul>
<li>The pie chart is an effective way of displaying the percentage breakdown of data by category.</li>
<li>The size of angle (°) is determined based on the frequency of group/category</li>
<li>Useful if the relative sizes of the data components are to be emphasized Pie charts also provide an effective way of presenting ratio- or interval-scaled data after they have been organized into categories</li>
<li>How to compute angle/degree? <span class="math display">\[
x^{\circ} = \frac{f}{\sum{x}} \times 360
\]</span> <img src="images/ch2/picture5.png" class="img-fluid" width="500" alt="Figure 4: Pie – Condition of gym facilities"></li>
</ul>
<p><strong>Bar Charts</strong></p>
<ul>
<li>Another common method for graphically presenting nominal and ordinal scaled data</li>
<li>One bar is used to represent the frequency for each category</li>
<li>The bars are usually positioned vertically with their bases located on the horizontal axis of the graph</li>
<li>The bars are separated, and this is why such a graph is frequently used for nominal and ordinal data – the separation emphasize the plotting of frequencies for distinct categories</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture6.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 5: Bar Chart – Condition of gym facilities</figcaption><p></p>
</figure>
</div>
<p><strong>Stem and Leaf</strong></p>
<p>A <em>stem and leaf plot</em> is a data plot that uses part of a data value as the stem and part of the data value as the leaf to form groups or classes.</p>
<p><img src="images/ch2/picture7.png" class="img-fluid" width="500"></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture8.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 6: Stem-and-Leaf Diagram</figcaption><p></p>
</figure>
</div>
</section>
<section id="numerical-descriptive-measures-ungrouped" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="numerical-descriptive-measures-ungrouped"><span class="header-section-number">2.3</span> Numerical descriptive measures (ungrouped)</h2>
<ul>
<li>Measures of central tendency (mean, median, mode)</li>
<li>Measure of variation (range, standard deviation, variance, coefficient of variation</li>
<li>Measure of skewness</li>
<li>Measures of Position (Q1, Q2, and Q3)</li>
</ul>
<center>
<img src="images/ch2/picture9.png" class="img-fluid" width="600">
</center>
<section id="measures-of-central-tendency" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="measures-of-central-tendency"><span class="header-section-number">2.3.1</span> Measures of Central Tendency</h3>
<p><strong>Mean</strong></p>
<p>The mean is the quotient of the sum of the values and the total number of values. The symbol <span class="math inline">\(\bar{x}\)</span> is used for <strong>sample mean</strong> and is given by the following formula:</p>
<p><span class="math display">\[
\bar{x} = \frac{x_1 + x_2 + x_3 + ... + x_{n-1} + x_n}{n} = \frac{\sum{x}}{n}
\]</span> For a population, the Greek letter <span class="math inline">\(\mu\)</span> (mu) is used for the mean.</p>
<p><span class="math display">\[
\bar{X} = \frac{X_1 + X_2 + X_3 + ... + X_{n-1} + X_N}{N} = \frac{\sum{X}}{N}
\]</span></p>
<p><span style="color:green;"><strong>Example 2.1</strong></span></p>
<p>The number of calls that a local police department responded to for a sample of 9 months is shown. Find the mean.</p>
<center>
475, 447, 440, 761, 993, 1052, 783, 671, 621
</center>
<p><span style="color:red;"><strong>Answer</strong></span></p>
<p><span class="math display">\[
\begin{aligned}
\bar{x} = \frac{\sum{x}}{n} &amp;= \frac{475+447+440+761+993+1052+783+671+621}{9} \\
&amp;= \frac{6243}{9} \approx 693.7
\end{aligned}
\]</span></p>
<p><strong>Interpretation:</strong> On average, the number of calls responded by local police department is approximately 694 calls.</p>
<p><span style="color:green;"><strong>Example 2.2</strong></span></p>
<p>A climatologist recorded daily temperature in Sungai Petani for twelve days. The data points are as follows (in degrees Celsius):</p>
<center>
30.5, 31.2, 29.8, 30.0, 30.7, 31.5, 29.9, 30.3, 30.1, 31.0, 30.4, 31.8
</center>
<p>Calculate the mean of daily temperature, and interpretation of the meaning of the mean value.</p>
<p><span style="color:red;"><strong>Answer</strong></span></p>
<p><span class="math display">\[
\begin{aligned}
\bar{x} &amp;= \frac{30.5+31.2+29.8+30.0+30.7+31.5+29.9+30.3+30.1+31.0+30.4+31.8}{12} \\
&amp;= 30.75^\circ C
\end{aligned}
\]</span> On average, the daily temperatures in Sungai Petani for twelve days is <span class="math inline">\(30.75^\circ C\)</span>.</p>
<p><span style="color:green;"><strong>Example 2.3</strong></span></p>
<p>In a bakery, the number of doughnuts sold in 7 days is recorded as follows:</p>
<center>
53, 60, 45, 77, 58, 42, 68
</center>
<p><span style="color:red;"><strong>Answer</strong></span></p>
<p><span class="math display">\[
\begin{aligned}
\bar{x} &amp;= \frac{53 + 60 + 45 + 77 + 58 + 42 + 68}{7} \\
&amp;= 57.57
\end{aligned}
\]</span></p>
<p>On average, the number of doughnuts sold in seven days is approximately 58 doughnuts.</p>
<p><strong>Properties of the Mean</strong></p>
<ul>
<li>Found by using all the values of data.</li>
<li>Varies less than the median or mode.</li>
<li>Used in computing other statistics, such as the variance.</li>
<li>Unique, usually not one of the data values.</li>
<li>Cannot be used with open-ended classes.</li>
<li>Affected by extremely high or low values, called outliers.</li>
</ul>
<p><strong>Median</strong></p>
<p>The <strong>median</strong> is the midpoint of the data array. The symbol for the median is <span class="math inline">\(\tilde{x}\)</span>. How to identify median value?</p>
<ol type="i">
<li>Sort the data in ascending order</li>
<li>Identify the location of median using</li>
<li>Determine the value of median</li>
</ol>
<ul>
<li>If the number of data (n) is ODD, the value is in the middle of sequence</li>
<li>If the number of data (n) is EVEN, the value of median is average of 2 middle values</li>
</ul>
<p><span style="color:green;"><strong>Example 2.4</strong></span></p>
<p>The number of police officers killed in the line of duty over the last 11 years is shown. Find the median.</p>
<center>
175 152 121 142 188 154 160 165 148 156 239
</center>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<ol type="i">
<li>Sort the data in ascending order</li>
</ol>
<center>
121, 142, 148, 152, 154, 156, 160, 165, 175, 188, 239
</center>
<p>ii Identify the location of median:</p>
<p><span class="math display">\[
\frac{11 + 1}{2} = 6^{th}
\]</span></p>
<ol start="3" type="i">
<li>Select the middle value, <span class="math inline">\(\tilde{x} = 156\)</span></li>
</ol>
<p><span style="color:green;"><strong>Example 2.5</strong></span></p>
<p>The number of tornadoes that have occurred in the certain country over an 8-year period follows.</p>
<center>
684, 764, 656, 702, 856, 1133, 1132, 1303
</center>
<p>Find the median.</p>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<p>Since the data given is even-number, there will be two values in the middle.</p>
<ol type="i">
<li>Sort the data in ascending order</li>
</ol>
<center>
656, 684, 702, 764, 856, 1132, 1133, 1303
</center>
<p>ii Identify the location of median:</p>
<p><span class="math display">\[
\frac{8 + 1}{2} = 4.5^{th}
\]</span></p>
<ol start="3" type="i">
<li>Select the middle value, <span class="math inline">\(\tilde{x} = \frac{764 + 856}{2} = \frac{1620}{2} = 810\)</span></li>
</ol>
<p><strong>Interpretation of median:</strong> Half of the tornadoes that have occurred in a certain country is less than or equal to 810 of tornadoes.</p>
<p><strong>Properties of Median</strong></p>
<ul>
<li>Give the midpoint.</li>
<li>Used when it is necessary to find out whether the data values fall into the upper half or lower half of the distribution.</li>
<li>Can be used for an open-ended distribution.</li>
<li>Affected less than the mean by extremely high or extremely low values.</li>
</ul>
<p><strong>Mode</strong></p>
<p>The <strong>mode</strong> is the value that occurs most often in a data set. It is sometimes said to be the most typical case. There may be no mode, one mode (unimodal), two modes (bimodal), or many modes (multimodal). Symbol of the mode is <span class="math inline">\(\hat{x}\)</span>.</p>
<p><span style="color:green;"><strong>Example 2.6</strong></span></p>
<p>Find the mode of the signing bonuses of eight football players for a specific year. The bonuses in thousands of ringgit Malaysia (RM) are:</p>
<center>
18.0, 14.0, 34.5, 10, 11.3, 10, 12.4, 10
</center>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<p>You may find it easier to sort first.</p>
<center>
<strong>10, 10, 10,</strong> 11.3, 12.4, 14.0, 18.0, 34.5
</center>
<p>Select the value that occurs the most.</p>
<p><strong>Interpretation:</strong> Most of the players signed the bonuses of 10 thousand ringgits Malaysia.</p>
<p><span style="color:green;"><strong>Example 2.7</strong></span></p>
<p>The data show the number of licensed nuclear reactors in the certain country for a recent 15-year period. Find the mode.</p>
<center>
103 103 103 103 103 106 108 108 108 110 108 112 112 112 108
</center>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<p>103 and 108 both occur the most. The data set is said to be bimodal. The modals are 103 and 108.</p>
<p><strong>Properties of mode</strong></p>
<ul>
<li>Used when the most typical case is desired.</li>
<li>Easiest average to compute.</li>
<li>Can be used with nominal data.</li>
<li>Not always unique or may not exist.</li>
</ul>
<p><strong>Distributions Shape</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture10.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 7: a) Positively skewed or right-skewed</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture11.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 7: b) Symmetrical distribution since mean, mode and median are equal</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture12.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 7: c) Negatively skewed or left-skewed</figcaption><p></p>
</figure>
</div>
</section>
<section id="measure-of-variation" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="measure-of-variation"><span class="header-section-number">2.3.2</span> Measure of variation</h3>
<p>Measures of variation include range, standard deviation, variance, and coefficient of variation.</p>
The <strong>range</strong> is the difference between the highest and lowest values in a data set.
<center>
Range = Highest – Lowest
</center>
<p>The <strong>population variance</strong> is the average of the squares of the distance each value is from the mean.</p>
<p>The <strong>standard deviation</strong> is the square root of the variance.</p>
<p><span style="color:green;"><strong>Example 2.8</strong></span></p>
<p>The table below shows the life-long (in months) of two brands of paint.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Brand XX</th>
<th style="text-align: center;">Brand YY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">35</td>
</tr>
<tr class="even">
<td style="text-align: center;">60</td>
<td style="text-align: center;">45</td>
</tr>
<tr class="odd">
<td style="text-align: center;">50</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">40</td>
</tr>
<tr class="even">
<td style="text-align: center;">20</td>
<td style="text-align: center;">25</td>
</tr>
</tbody>
</table>
<p>Determine the mean and standard deviation for the above data.</p>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<p><span style="color:blue;"> Brand XX: <span class="math inline">\(\mu = mean = \frac{\sum{x}}{N} = \frac{210}{6} = 35\)</span> and <span class="math inline">\(Range = 60 - 10 = 50\)</span>. </span></p>
<p>Brand YY: <span class="math inline">\(\mu = mean = \frac{\sum{x}}{N} = \frac{210}{6} = 35\)</span> and <span class="math inline">\(Range = 45 -25 = 20\)</span>.</p>
<p>The average for both brands is the same, but the range for Brand XX is much greater than the range for Brand YY. Which brand would you buy?</p>
<p><strong>Uses of the Variance and Standard Deviation</strong></p>
<ul>
<li>To determine the spread of the data.</li>
<li>To determine the consistency of a variable.</li>
<li>To determine the number of data values that fall within a specified interval in a distribution (Chebyshev’s Theorem).</li>
<li>Used in inferential statistics.</li>
</ul>
<p>Population variance:</p>
<p><span class="math display">\[
\sigma^2 = \frac{\sum{(X - \mu)^2}}{N}
\]</span></p>
<p>Population Standard Deviation</p>
<p><span class="math display">\[
\sigma = \sqrt{ \frac{\sum{(X - \mu)^2}}{N}}
\]</span></p>
<p>Sample variance:</p>
<p><span class="math display">\[
s^2 = \frac{\sum{(X - \bar{X})^2}}{n-1}\ \ \ or\ \ \ s^2 = \frac{1}{n-1}\left[\sum{X^2} - \frac{(\sum{X})^2}{n}\right]
\]</span></p>
<p>Sample Standard Deviation:</p>
<p><span class="math display">\[
s = \sqrt{\frac{\sum{(X - \bar{X})^2}}{n-1}}\ \ \ or\ \ \ s = \sqrt{\frac{1}{n-1}\left[\sum{X^2} - \frac{(\sum{X})^2}{n}\right]}
\]</span></p>
<p>The <strong>coefficient of variation</strong> is the standard deviation divided by the mean, expressed as a percentage.</p>
<p><span class="math display">\[
Coefficient\ of\ Variation\ (CV)\ = \frac{s}{x} \times 100\%
\]</span></p>
<p><span style="color:green;"><strong>Example 2.9</strong></span></p>
<p>The mean of the number of sales of cars over a 3-month period is 87, and the standard deviation is 5. The mean of the commissions is $5225, and the standard deviation is $773. Compare the variations of the two.</p>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<p><span style="color:blue;"><span class="math inline">\(CV_{Sales} = \frac{5}{87} \times 100\% = 5.7\%\)</span></span></p>
<p><span class="math inline">\(CV_{Commissions} = \frac{773}{5225} \times 100\% = 14.8\%\)</span></p>
<p>The data distribution for Commissions are more dispersed than sales. Similarly, Sales data distribution is more consistent than the data distribution in commissions.</p>
<p><span style="”color:green;”"><strong>Example 2.10</strong></span></p>
<p>A meteorologist is studying the monthly rainfall patterns in two different regions, Region A and Region B, over the past year. They have collected data for 11 months (in mm). The goal is to determine which region has more dispersed rainfall. Calculate the coefficient of variation for each region’s monthly rainfall data and identify which region’s data is more dispersed.</p>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture13.png" class="img-fluid figure-img" width="400"></p>
<p></p><figcaption class="figure-caption">SPSS Output</figcaption><p></p>
</figure>
</div>
</center>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<p><span style="color:blue;"><span class="math inline">\(CV_{Region A} = \frac{\sqrt{43.634}}{36.5427} \times 100\% = 18.08\%\)</span></span></p>
<p><span class="math inline">\(CV_{Region B} = \frac{\sqrt{9.894}}{60.5745} \times 100\% = 5.19\%\)</span></p>
<p>Region A has a more dispersed rainfall pattern than Region B.</p>
</section>
<section id="measure-of-skewness" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="measure-of-skewness"><span class="header-section-number">2.3.3</span> Measure of skewness</h3>
<p>Skewness is the measurement of the lack of symmetry of the distribution. There are several measures for expressing the amount of skewness, but the only important one is the Pearson Coefficient of Skewness:</p>
<p><span class="math display">\[
PCS = \frac{mean - mode}{standard\ deviation}\ \ \ \ or\ \ \ \ PCS = \frac{3(mean - median)}{standard\ deviation}
\]</span></p>
<p><strong>Skewness</strong></p>
<p>It is the <em>degree of distortion</em> from the symmetrical bell curve or the normal distribution. It measures the lack of symmetry in data distribution. It differentiates extreme values in one versus the other tail. A symmetrical distribution will have a skewness of 0.</p>
<p>There are two types of Skewness: <strong>Positive</strong> and <strong>Negative</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture14.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 8: Types of Skewness</figcaption><p></p>
</figure>
</div>
<p><span style="color:green;"><strong>Example 2.11</strong></span></p>
<p>The SPSS output gives information on descriptive statistics on the number of licensed nuclear reactors in the certain country for a recent 15-year period. Find the Person Coefficient of Skewness. Hence identify the shape of distribution.</p>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture15.png" class="img-fluid figure-img" width="400"></p>
<p></p><figcaption class="figure-caption">SPSS Output</figcaption><p></p>
</figure>
</div>
</center>
<p><span class="math display">\[
\begin{aligned}
PCS &amp;= \frac{3(\bar{x} - \tilde{x})}{s} \\
&amp;= \frac{3(107.6 - 108)}{5.193} \\
&amp;= -0.2311
\end{aligned}
\]</span></p>
<p>Negatively skewed.</p>
<p><span style="color:green;"><strong>Example 2.12</strong></span></p>
<p>The table below shows the number of eggs laid by 20 chickens over a 30-day period in a small poultry farm. Calculate the Pearson Coefficient of Skewness. Hence identify the shape of distribution.</p>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture16.png" class="img-fluid figure-img" width="400"></p>
<p></p><figcaption class="figure-caption">SPSS Output</figcaption><p></p>
</figure>
</div>
</center>
<p><span class="math display">\[
\begin{aligned}
PCS &amp;= \frac{\bar{x} - \hat{x}}{s} \\
&amp;= \frac{38.55 - 42}{6.809} \\
&amp;= -0.5067
\end{aligned}
\]</span></p>
<p>Negatively skewed.</p>
</section>
<section id="measures-of-position-q-q2-and-q3" class="level3" data-number="2.3.4">
<h3 data-number="2.3.4" class="anchored" data-anchor-id="measures-of-position-q-q2-and-q3"><span class="header-section-number">2.3.4</span> Measures of Position (Q, Q2, and Q3)</h3>
<p><strong>Quartiles</strong> separate the data set into 4 equal groups. <span class="math inline">\(Q_1 = P_{25}\)</span>, <span class="math inline">\(Q_2 = MD\)</span>, <span class="math inline">\(Q_3 = P_{75}\)</span></p>
<p>The <strong>Interquartile Range</strong>, <span class="math inline">\(IQR = Q_3 – Q_1\)</span>.</p>
<p><span style="color:green;"><strong>Example 2.13</strong></span></p>
<p>Find <span class="math inline">\(Q_1\)</span>, <span class="math inline">\(Q_2\)</span>, and <span class="math inline">\(Q_3\)</span> for the data set.</p>
<center>
15, 13, 6, 5, 12, 50, 22, 18
</center>
<p><span style="color:red;"><strong>Answer:</strong></span></p>
<p>Sort in ascending order.</p>
<center>
5, 6, 12, 13, 15, 18, 22, 50
</center>
<p>Location: <span class="math inline">\(Q_1 = \frac{n + 1}{4}\)</span> → <span class="math inline">\(Q_1 = \frac{8 + 1}{4} = 2.25^{th}\)</span> in the array.</p>
<p>Value of Q1: <span class="math inline">\(X_{Q_1} = 6 + 0.25 (12 - 6) = 7.5\)</span></p>
<p>Location: <span class="math inline">\(Q_2 = \frac{n + 1}{2}\)</span> → <span class="math inline">\(Q_2 = \frac{8 + 1}{2} = 4.5^{th}\)</span> in the array.</p>
<p>Value of Q2: <span class="math inline">\(X_{Q_2} = 13 + 0.5 (15 - 13) = 14\)</span></p>
<p>Location: <span class="math inline">\(Q_3 = 3(\frac{n + 1}{4})\)</span> → <span class="math inline">\(Q_3 = 3(\frac{8 + 1}{4}) = 6.75^{th}\)</span> in the array.</p>
<p>Value of Q3: <span class="math inline">\(X_{Q_3} = 18 + 0.75 (22 - 18) = 21\)</span></p>
<p>An <strong>outlier</strong> is an extremely high or low data value when compared with the rest of the data values. A data value less than Q1 – 1.5(IQR) or greater than Q3 + 1.5(IQR) can be considered an outlier.</p>
</section>
<section id="box-and-whisker-plot" class="level3" data-number="2.3.5">
<h3 data-number="2.3.5" class="anchored" data-anchor-id="box-and-whisker-plot"><span class="header-section-number">2.3.5</span> Box-and-whisker plot</h3>
<p>Also known as box plots, they display a <strong>five-number summary</strong> of a set of data. Consist of - (i) minimum, (ii) first quartile, (iii) median, (iv) third quartile, and (v) maximum values.</p>
<p>Able to identify the centre, the spread, and the skewness of the data</p>
<p><span style="color:green;"><strong>Example 2.14</strong></span></p>
<p>The number of meteorites found in 10 U.S. states is shown. Construct a boxplot for the data. Hence, determine its skewness.</p>
<center>
89, 47, 164, 296, 30, 215, 138, 78, 48, 39 30, 39, 47, 48, 78, 89, 138, 164, 215, 296
</center>
<p>Five-Number Summary: 30; 47; 83.5; 164; 296</p>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture17.png" class="img-fluid figure-img" width="400"></p>
<p></p><figcaption class="figure-caption">Figure 9: Skewed to the right / right skewness / positively skewed</figcaption><p></p>
</figure>
</div>
</center>
<p><span style="color:green;"><strong>Example 2.15</strong></span></p>
<p>A meteorologist is studying the monthly rainfall patterns in two different regions, Region A and Region B, over the past year. They have collected data for 11 months (in mm). They determine the skewness of the two regions based on box and whiskers plot.</p>
<p><span style="color:red;"><strong>Answer :</strong></span></p>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture18.png" class="img-fluid figure-img" width="400"></p>
<p></p><figcaption class="figure-caption">SPSS Output</figcaption><p></p>
</figure>
</div>
</center>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture19.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Figure 9: Region A – positively skewed; Region B – Approximately normal</figcaption><p></p>
</figure>
</div>
</center>
</section>
</section>
<section id="spss-output-on-numerical-descriptive-statistics" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="spss-output-on-numerical-descriptive-statistics"><span class="header-section-number">2.4</span> SPSS Output on Numerical Descriptive Statistics</h2>
<p>IBM statistical software provides a wide range of statistical analysis and graphing capabilities. We use dataset from SPSS’s samples so that students can have free access to it and be able to run it by themselves to produce the SPSS output on descriptive statistics.</p>
<p>Data: <strong>aflatoxin20.sav</strong> Description: This data consists of 32 poison concentrations which are measured in parts per billion (PPB) on corn crops. This poison is known as aflatoxin. The concentration varies widely within crop yields.</p>
<p>To open a data file: From the menus choose: File &gt; Open &gt; Data… A dialog box for opening files is displayed and choose <strong>aflatoxin20.sav</strong></p>
<p>To obtain the descriptive analysis of the data:<br>
1. From the menus choose:<br>
Analyze &gt; Descriptive Statistics &gt; Frequencies…<br>
The Frequencies dialog box is displayed.<br>
2. Double click on <strong><em>Aflatoxin PPB [toxin]</em></strong><br>
<img src="images/ch2/picture20.png" class="img-fluid"><br>
3. Click on <strong>Statistics</strong> and choose as per figure below:<br>
<img src="images/ch2/picture21.png" class="img-fluid"><br>
4. Click <strong>Continue</strong><br>
5. Click <strong>OK</strong> to run the procedure. Results are displayed in the Viewer window.<br>
<img src="images/ch2/picture22.png" class="img-fluid"><br>
</p>
</section>
<section id="exercise-2" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="exercise-2"><span class="header-section-number">2.5</span> Exercise 2</h2>
<ol type="1">
<li>The weight (kg) of 12 customers registered for WX fitness studio are as follows.
<center>
110, 90, 65, 100, 95, 75, 90, 85, 80, 70, 75, 90
</center></li>
</ol>
<ol type="a">
<li>Find the mode and comment on the value obtained.</li>
<li>Calculate the mean and standard deviation.</li>
<li>Describe the shape of distribution by using an appropriate measurement.</li>
</ol>
<ol start="2" type="1">
<li>A researcher studied petrol usage (in littles) for 14 cars travelling from town A to town B in a month. The data collected is shown below:
<center>
81, 80, 65, 105, 144, 75, 150, 96, 91, 68, 135, 134, 95, 124
</center></li>
</ol>
<ol type="a">
<li>Find the first quartile, median, and third quartile.</li>
<li>Construct a box-and-whiskers plot for the above data.</li>
<li>Determine the shape of the data distribution based on the box-and-whiskers plot.</li>
</ol>
<ol start="3" type="1">
<li>The number of current issues books sold in a week by 12 bookstores at town A is as follows.
<center>
11, 23, 12, 15, 22, 10, 16, 15, 7, 12, 26, 14
</center></li>
</ol>
<ol type="a">
<li>Find the mean and the mode.</li>
<li>By comparing the mean and the mode in (a), determine the shape of the distribution for the above data.</li>
<li>Calculate the first quartile, median and third quartile of the above data.</li>
</ol>
<ol start="4" type="1">
<li>The chemistry test marks of eight randomly selected students are given below:
<center>
85, 65, 48, 70, 30, 80, 92, 70
</center></li>
</ol>
<ol type="a">
<li>Calculate the mean, median and mode for the test score.</li>
<li>Find the variance of the test score for the selected students.</li>
<li>Determine the shape of the distribution of the test score using Pearson’s coefficient of skewness.</li>
</ol>
<ol start="5" type="1">
<li>The output below refers to National unemployment rate prior to the coronavirus outbreak (Covid-19).
<center>
<img src="images/ch2/picture23.png" class="img-fluid" width="400" alt="SPSS Output">
</center></li>
</ol>
<ol type="a">
<li>Determine the value of <strong>A</strong>.</li>
<li>Find the value of Pearson Coefficient of Skewness. Then, identify the shape of distribution.</li>
<li>Based on information given in the output, sketch the appropriate diagram to represent the shape of distribution for unemployment rate.</li>
</ol>
<ol start="6" type="1">
<li>A company is considering installing a new machine to assemble its product. The company is considering two types of machines, but it will buy only one type. The company selected eight assembly workers and asked them to use these two types of machines to assemble products. The data for two random samples is shown in Table 1. Table 2 shows the summary of the statistics for the time taken for the two types of machines based on data in Table 1.</li>
</ol>
<center>
<p>Table 1: Time taken (in minutes) to assemble one unit of product on each machine</p>
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Machine 1</strong></td>
<td>23</td>
<td>26</td>
<td>19</td>
<td>24</td>
<td>27</td>
<td>22</td>
<td>20</td>
<td>18</td>
</tr>
<tr class="even">
<td><strong>Machine 2</strong></td>
<td>21</td>
<td>24</td>
<td>23</td>
<td>25</td>
<td>24</td>
<td>28</td>
<td>24</td>
<td>23</td>
</tr>
</tbody>
</table>
Table 2: Summary Statistics <img src="images/ch2/picture24.png" class="img-fluid" width="400">
</center>
<ol type="a">
<li>Compute the value of <strong>A</strong> and <strong>B</strong>.</li>
<li>Determine which machine is more consistent in their time taken to assemble one-unit product.</li>
</ol>
<ol start="7" type="1">
<li>The weight of chickens (in kg) in small poultry in Klebang were summarize as follows:
<center>
<img src="images/ch2/picture25.png" class="img-fluid" width="700">
</center></li>
</ol>
<ol type="a">
<li>Calculate the mean and standard deviation.</li>
<li>Determine the median value.</li>
<li>Interpret the value obtain in (b).</li>
<li>State the name of the plot.</li>
</ol>
</section>
<section id="answers-to-exercise-2" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="answers-to-exercise-2"><span class="header-section-number">2.6</span> Answers to Exercise 2</h2>
<ol type="1">
<li><ol type="a">
<li>Mode = 90 kg. Most frequently weight of the customers for WX fitness studio is 90 kg.</li>
<li>Mean = 85.42, s = 13.0486</li>
<li>PMS = -0.3510. The distribution of data is skewed to the left.</li>
</ol></li>
<li><ol type="a">
<li>Median (Q2) = 95.5, Q1 = 78.75, Q3 = 134.25</li>
<li>The shape of the data distribution is skewed to the right.</li>
</ol></li>
<li><ol type="a">
<li>Mean = 15.25, Mode = 12 and 15</li>
<li>Since Mean &gt; Mode, the shape of the distribution for the above data is skewed to the right.</li>
<li>Q1 = 11.25, Q2 = 14.5, Q3 = 20.5</li>
</ol></li>
<li><ol type="a">
<li>Mean = 67.5, median = 70, Mode = 70.</li>
<li>Variance = 409.714</li>
<li>PCS = -0.1235. The shape of the distribution of the test score is skewed to the left.</li>
</ol></li>
<li><ol type="a">
<li>A = 10</li>
<li>PCS = 0.5111 (positive skewness)</li>
<li><img src="images/ch2/picture26.png" class="img-fluid" width="400"></li>
</ol></li>
</ol>
<p>6 a) A = 22.5; B = 24.0 b) CV1 = 14.52%; CV2 = 8.33% c) Machine 2 is more consistent in time taken to assemble one unit of product compared to Machine 1.</p>
<ol start="7" type="1">
<li><ol type="a">
<li>Mean = 3.71 kg, s = 0.7022</li>
<li>Median = 3.65 kg</li>
<li>Half of the chicken’s weights are less than 3.65kg and another half of the chickens weigh more than 3.65 kg.</li>
<li>Stem and leaf plot.</li>
</ol></li>
</ol>
</section>
<section id="tutorial-2" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="tutorial-2"><span class="header-section-number">2.7</span> Tutorial 2</h2>
<ol type="1">
<li>The descriptive statistics for the life span (in years) of brand AA washing machine are summarized as below.</li>
</ol>
<p>Descriptive Statistics</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>N</td>
<td>Mean</td>
<td>Mode</td>
<td>Std. Deviation</td>
<td>Minimum</td>
<td>Maximum</td>
</tr>
<tr class="even">
<td>Life span (years)</td>
<td>89</td>
<td>6.59</td>
<td>7.04</td>
<td>0.74</td>
<td>5.2</td>
<td>8.1</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Calculate the coefficient of skewness. Hence, comment on the shape of the distribution.</li>
<li>Explain the meaning of the mode value.</li>
<li>Given the mean and variance for the life span (in years) of brand BB were 7.1 and 12.3 respectively. Using an appropriate measurement, determine which brand has a more consistent life span.</li>
</ol>
<ol start="3" type="1">
<li>Waiting times (in minutes) of customers at the Providence Bank (PB) and the Valley Bank (VB) are given as follows.</li>
</ol>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
</colgroup>
<tbody>
<tr class="odd">
<td>PB</td>
<td>3.2</td>
<td>4.4</td>
<td>4.8</td>
<td>5.2</td>
<td>6.2</td>
<td>6.7</td>
<td>7.5</td>
<td>8.0</td>
<td>6.5</td>
<td>9.0</td>
<td>5.1</td>
<td>3.3</td>
<td>5.2</td>
<td>4.0</td>
<td>4.9</td>
</tr>
<tr class="even">
<td>VB</td>
<td>5.8</td>
<td>5.6</td>
<td>5.7</td>
<td>5.8</td>
<td>6.1</td>
<td>6.4</td>
<td>6.7</td>
<td>6.7</td>
<td>6.7</td>
<td>6.8</td>
<td>6.5</td>
<td>7.0</td>
<td>6.9</td>
<td>6.5</td>
<td>6.4</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Calculate the mean and standard deviation for Valley Bank waiting times.</li>
<li>From the above box-and-whisker plots of waiting times for both Providence and Valley banks, comment on the shape of distribution for each plot.</li>
<li>The mean and standard deviation for Providence Bank are 5.6 and 1.692 respectively. Determine which bank shows a more consistent wait time.</li>
</ol>
<ol start="3" type="1">
<li>The stem and leaf plot below represents the History test scores (out of 100) of 15 randomly selected students in Class A.</li>
</ol>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture27.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Key: 4|3 means 43</figcaption><p></p>
</figure>
</div>
</center>
<ol type="a">
<li>Calculate the mean and standard deviation for the test score.</li>
<li>Interpret the mean obtained in a).</li>
<li>The summary statistics of the test score for History and Geography students in Class A are summarized in the following table. Using an appropriate measure, determine which distribution of the test score between the subjects is more dispersed.</li>
</ol>
<center>
<p>Descriptive statistics</p>
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 29%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>N</strong></td>
<td><strong>Mean</strong></td>
<td><strong>Std. Deviation</strong></td>
</tr>
<tr class="even">
<td><strong>History</strong></td>
<td>15</td>
<td>65.4667</td>
<td>11.1859</td>
</tr>
<tr class="odd">
<td><strong>Geography</strong></td>
<td>17</td>
<td>66.9412</td>
<td>17.5623</td>
</tr>
</tbody>
</table>
</center>
<ol start="4" type="1">
<li>The following chart shows the recorded weekly milk yield (in the nearest kg) for each cow selected at random from Farm A.</li>
</ol>
<center>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ch2/picture28.png" class="img-fluid figure-img" width="500"></p>
<p></p><figcaption class="figure-caption">Key: 12|9 means 129</figcaption><p></p>
</figure>
</div>
</center>
<ol type="a">
<li>State the name of the above chart.</li>
<li>Find the median weekly milk yield recorded at Farm A. Hence, interpret the result.</li>
<li>The statistics for the weekly milk yields for Farm A and Farm B are summarized in the following table. Using an appropriate measure, determine which farm has more consistent weekly milk yield.</li>
</ol>
<center>
<p>Descriptive statistics</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 29%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>N</strong></td>
<td><strong>Mean</strong></td>
<td><strong>Std. Deviation</strong></td>
</tr>
<tr class="even">
<td><strong>Farm A</strong></td>
<td>24</td>
<td>148.7</td>
<td>13.7</td>
</tr>
<tr class="odd">
<td><strong>Farm B</strong></td>
<td>28</td>
<td>158.5</td>
<td>8.33</td>
</tr>
</tbody>
</table>
</center>
<ol start="5" type="1">
<li>The following chart summarizes the weight in kilograms of 17 male and female Orang Utans in the Reserves Centre.</li>
</ol>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 27%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Gender</strong></td>
<td><strong>Mean</strong></td>
<td><strong>Std. Deviation</strong></td>
<td><strong>Minimum</strong></td>
<td><strong>Maximum</strong></td>
</tr>
<tr class="even">
<td>Male</td>
<td>117.94</td>
<td>13.32</td>
<td>100</td>
<td>150</td>
</tr>
<tr class="odd">
<td>Female</td>
<td>97.65</td>
<td>17.79</td>
<td>65</td>
<td>120</td>
</tr>
</tbody>
</table>
<center>
<img src="images/ch2/picture29.png" class="img-fluid" width="500">
</center>
<ol type="a">
<li>Name the diagram given.</li>
<li>Identify the outlier(s), if any.</li>
<li>Using an appropriate measure, determine which gender is more consistent in distribution of weight.</li>
</ol>
<ol start="6" type="1">
<li>The weekly consumption of cheese (in ounces) for 35 participants in a nutrition study is summarize as follows:</li>
</ol>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 5%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 5%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>N</td>
<td><span class="math inline">\(\sum{x}\)</span></td>
<td><span class="math inline">\(\sum{x^2}\)</span></td>
<td>W</td>
</tr>
<tr class="even">
<td>Cheese (in ounces)</td>
<td>25</td>
<td>265</td>
<td>4579</td>
<td>10</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Calculate the mean and standard deviation</li>
<li>Most participants spent 10 ounces of cheese weekly. Based on the given interpretation, name the statistical measure of W.</li>
<li>Identify the skewness of the weekly consumption of cheese using appropriate measurement.</li>
</ol>
</section>
<section id="answers-to-tutorial-2" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="answers-to-tutorial-2"><span class="header-section-number">2.8</span> Answers to Tutorial 2</h2>
<p>1 a) Coefficient of skewness = -0.6081 The shape of the distribution is skewed to the left. b) Mode =7.04 Most of the life span of Brand AA washing machine is 7.04 years. c) CV for Brand AA = 11.23%, CV for Brand BB = 49.40% Therefore, Brand AA has a more consistent of life span.</p>
<ol start="2" type="1">
<li><ol type="a">
<li>Mean = 6.373, s = 0.462</li>
<li>The shape of the distribution of PB is skewed to the right. The shape of the distribution of VB is skewed to the left.</li>
</ol></li>
<li><ol type="a">
<li>Mean = 65.467, n = 15, s = 11.186</li>
<li>The average test score of History is 65.467.</li>
<li>History test scores is more consistent the Geography test scores.</li>
</ol></li>
<li><ol type="a">
<li>Stem-and-Leaf Plot</li>
<li>Median = 147 kg 50% of the weekly milk yield is less than 147 kg.</li>
<li>Farm B has more consistent weekly milk yield.</li>
</ol></li>
<li><ol type="a">
<li>Box and Whisker Plot</li>
<li>Outliers : 16, 17</li>
<li>Male is more consistent in distribution of weight.</li>
</ol></li>
<li><ol type="a">
<li>Mean = 10.6 ounces, s = 8.588</li>
<li>Mode</li>
<li>PCS = 0.07 (approximately normal)</li>
</ol></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-estimation.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estimation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Statistics for Business and Social Sciences was authored by Rosidah Ahmad and edited by Kamarul Ariffin Mansor, Ida Normaya Mohd Nasir, and Norin Rahayu Shamsuddin.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">This eBook contents was created with ❤️ by kammyariff</div>
  </div>
</footer>



</body></html>